word2vec:
  sg: 1
  vector_size: 200
  hs: 1
  window: 5
  min_count: 1
  workers: 1

materials_processing:
  property_list: ["dielectric", "conductivity"]

# Additional paths
abstracts_csv: "../01_collect_papers/files/papers_until_2023.csv"
materials_dir: "../material_systems/MaxDMinC"
output_dir: "selection_results/MaxDMinC"